apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.srcPort }}
      targetPort: {{ .Values.service.dstPort }}
      protocol: {{ default "TCP" .Values.service.protocol }}
      name: {{ .Values.service.name | default "http" }}    
    {{- range $additionalPortIndex, $additionalPort := .Values.service.additionalPorts }}
    - port: {{ $additionalPort.srcPort }}
      targetPort: {{ $additionalPort.dstPort }}
      protocol: {{ default "TCP" $additionalPort.protocol }}
      name: {{ required ".Values.service.additionalPorts[].name is required and cannot be same with another port name" $additionalPort.name }}    
    {{- end }}
  selector:
    {{- include "base.selectorLabels" . | nindent 4 }}
