{{- if .Values.virtualService.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.virtualService.gateways }}
  {{- with .Values.virtualService.gateways }}
  gateways:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- else }}
  gateways:
    - mesh
  {{- end }}
  hosts:
    - {{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local
    - {{ .Release.Name }}
  http:
    - route:
        - destination:
            host: {{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local
            subset: v1
      {{- with .Values.virtualService.retries }}
      retries:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}