{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sync-secret.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sync-secret.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: vault-auth
type: kubernetes.io/service-account-token
{{- end }}